### PR TITLE
Usability improvements

### LINKED ISSUE #5: Add a README to each example project.
It will give a short explanation to what the project does and anything it implements (Usage of commands in WorldTest, using schedulers in SchedulerTest, etc.)

### PR DESCRIPTION
**Pull request by Katrix**
Yet another attempt at reviving this thing.

* Adds READMEs to plugins (Should contain information on how to compile and run eventually). Resolves #5 
* Minor improvements and updates
* (Not yet done) Add comments to projects other than Kotlin and Scala (I don't know how much comments there should be, but the current amount is too little)
* Provides information on relocation for Kotlin and Scala
* For Scala, should the sbt plugin I made to do a lot of the work be used?

### CODE REVIEW

**Comment by Meronat** [comment]
Thanks for the PR, I'll review it later. Relating to your sbt plugin, I don't see why not include it, if it makes the development experience more reliable and easier to set up. At least if you plan to maintain it for a bit :)

**Comment by Meronat** [comment]
@Katrix Is there anything else you'd like to finish before I merge this PR?

**Comment by Katrix** [comment]
Okay, don't think I'll get around to adding more to this before summer vacation. Just go ahead and pull.

Future works which need to be done. 
* A command plugin which explains how commands work.
* Comments for the Smite plugin
* Comments for WorldsTest plugin
* A description for TestSuite (what is it, and what is it used for)

**Comment by parlough** [comment]
Thanks @Katrix, appreciate it.

**Pull request merged**
