### PR TITLE
Adding command to smite players :)

### PR DESCRIPTION
**Pull request by jon077**
Fixed the compilation error and added an example of a command

### CODE REVIEW

**Comment by DDoS** [comment]
I'll merge this when I merge https://github.com/SpongePowered/SpongeAPI/pull/1360

**Comment by jon077** [comment]
Cool!  Let me know if I need to merge or help in anyway.

**Comment by Meronat** [comment]
Needs updating for API changes, if you don't want to that's okay, feel free to close!

**Comment by Meronat** [comment]
Thanks for the contribution, but going to close this due to inactivity. If you'd like to still get this is in, open an updated pull request.

Thank though!

**Pull request closed without merging**
