### PR TITLE
Simple Custom Data Example

### PR DESCRIPTION
**Pull request by Faithcaio**
#11

Custom Data implementing the base `AbstractData` and `AbstractImmutableData` classes.

@gabizou

### CODE REVIEW

**Comment by Faithcaio** [comment]
AbstractData will get replaced by generated Data classes

**Comment by gabizou** [comment]
Well @Faithcaio I was considering that if it's staying in API 5, it might as well be added, but marked as deprecated for API 6 (since that is potentially the target for custom data class generation), and then API 7 would remove the abstract data classes altogether.

**Comment by ZephireNZ** [comment]
@gabizou I worked on a complete example for my [Docs PR](https://github.com/SpongePowered/SpongeDocs/pull/532), that covered a broader range of stuff than just the manipulator alone. Simple and compound manipulators, serializables, etc. Maybe I should open another PR?

**Comment by Faithcaio** [comment]
#17

**Pull request closed without merging**
